# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 02:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='Username')),
                ('last_name', models.CharField(max_length=100, verbose_name='Lastname')),
                ('first_name', models.CharField(max_length=100, verbose_name='Firstname')),
                ('nickname', models.CharField(max_length=100, verbose_name='nickname')),
                ('email', models.EmailField(max_length=254)),
                ('date_joined', models.DateField(auto_now=True, verbose_name='가입한 날짜')),
                ('last_modified', models.DateField(auto_now_add=True, verbose_name='수정한 날짜')),
                ('following', models.ManyToManyField(related_name='_myuser_following_+', to='member.MyUser', verbose_name='Following User')),
            ],
        ),
    ]
