# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20170213_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='following',
            field=models.ManyToManyField(null=True, to='member.MyUser', verbose_name='Following User'),
        ),
    ]
