# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 05:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_remove_myuser_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='following',
            field=models.ManyToManyField(blank=True, to='member.MyUser', verbose_name='Following User'),
        ),
    ]
