# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0007_auto_20170213_1429'),
        ('post', '0002_auto_20170213_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='like_users',
            field=models.ManyToManyField(related_name='like_post_set', through='post.PostLike', to='member.MyUser'),
        ),
    ]
